# # ----------------------------------------------------------------------------
# # creating trough odoo
# # ----------------------------------------------------------------------------
# vals = {'calendar_last_notif_ack': datetime.datetime(2019, 11, 16, 16, 59, 15),
#  'category_id': [(6, 0, [])],
#  'color': 0,
#  'customer_rank': 0,
#  'email': False,
#  'image_1920': False,
#  'invoice_warn': 'no-message',
#  'is_company': False,
#  'is_sekretariat_or_higher': False,
#  'lang': 'en_US',
#  'last_name': 'Moldenhauer',
#  'last_semester': 0,
#  'message_bounce': 0,
#  'name': 'Rottermann Moldenhauer',
#  'picking_warn': 'no-message',
#  'property_account_payable_id': 13,
#  'property_account_position_id': False,
#  'property_account_receivable_id': 6,
#  'property_payment_term_id': False,
#  'property_stock_customer': 5,
#  'property_stock_supplier': 4,
#  'property_supplier_payment_term_id': False,
#  'prospect': False,
#  'sale_warn': 'no-message',
#  'supplier_rank': 0,
#  'trust': 'normal',
#  'type': 'contact',
#  'tz': 'Europe/Brussels'}

# vals_list = [{'calendar_last_notif_ack': datetime.datetime(2019, 11, 16, 17, 10, 51),
#   'category_id': [(6, 0, [])],
#   'color': 0,
#   'customer_rank': 0,
#   'email': False,
#   'image_1920': False,
#   'invoice_warn': 'no-message',
#   'is_company': False,
#   'is_sekretariat_or_higher': False,
#   'lang': 'en_US',
#   'last_name': 'Moldenhauer',
#   'last_semester': 0,
#   'message_bounce': 0,
#   'message_follower_ids': [(0,
#                             0,
#                             {'partner_id': 3,
#                              'res_model': 'res.partner',
#                              'subtype_ids': [(6, 0, [1])]})],
#   'name': 'Rottermann Moldenhauer',
#   'picking_warn': 'no-message',
#   'property_account_payable_id': 13,
#   'property_account_position_id': False,
#   'property_account_receivable_id': 6,
#   'property_payment_term_id': False,
#   'property_stock_customer': 5,
#   'property_stock_supplier': 4,
#   'property_supplier_payment_term_id': False,
#   'prospect': False,
#   'sale_warn': 'no-message',
#   'supplier_rank': 0,
#   'trust': 'normal',
#   'type': 'contact',
#   'tz': 'Europe/Brussels'}]
# # ----------------------------------------------------------------------------
# # end creating trough odoo
# # ----------------------------------------------------------------------------
create_sequence = [
  "student",
  "semester",
  "price_event",
  "university",
  "study_center",
  "grade",
  "reason_exmatriculation",
  "account_analytic_account",
  "study_course",
  "studies",
  "kohorte",
]
sample_data = {
    "student": {
        "module": "res.partner",
        # creating a student:
        # self ->res.partner()
        "search" : ["name", "last_name"], # do not create, when object is found using these elements
        "vals_list": [
            {
                "__last_update": False,
                "academic_title": False,
                "active": True,
                "additional_info": False,
                "ahv_number": "999.9999.9999.99",
                "assistant": False,
                "bfs_before_study_id": False,
                "bfs_school_code": False,
                "bfs_student_auth_id_code": False,
                "birthdate": "1999-01-05",
                "certification_date_before": 0,
                "city": False,
                "collaborator_ce": False,
                "comment": False,
                "company_id": False,
                "company_name": False,
                "country_at_auth_identification": False,
                "country_id": False,
                "country_now": False,
                "cover_letter": False,
                "cover_letter_fname": False,
                "customer_rank": 0,
                "cv_file": False,
                "cv_file_fname": False,
                "date_marketing": False,
                "diplomas_file": False,
                "diplomas_file_fname": False,
                "employee": False,
                "enable_contact_data": False,
                "expenses_remarks": False,
                "fields_visible": False,
                "first_name_for_reports": False,
                "for_matri_number": False,
                "foreign_school": False,
                "function": False,
                "function2_id": False,
                "function_id": False,
                "gender": "1",
                "id_cas_file": False,
                "id_cas_file_fname": False,
                "identity_card": False,
                "identity_card_fname": False,
                "image_1920": False,
                "inactive_teacher": False,
                "industry_id": False,
                "invoice_warn": "no-message",
                "invoice_with_post": False,
                "is_company": False,
                "lang": "de_CH",
                "last_name": "Fleissig",
                "last_name_for_reports": False,
                "link_cv": False,
                "matriculation_number": False,
                "mentoren_tutoren": False,
                "message_attachment_count": 0,
                "mobile": False,
                "moodle_id": 0,
                "moodle_pending_discharge": False,
                "moodle_pending_enrollment": False,
                "moodle_synced": False,
                "name": "Student",
                "other": False,
                "partner_gid": 0,
                "phone": False,
                "photo1": False,
                "photo2": False,
                "photo3": False,
                "picking_warn": "no-message",
                "profession": False,
                "property_account_payable_id": 13,
                "property_account_position_id": False,
                "property_account_receivable_id": 6,
                "property_payment_term_id": False,
                "property_stock_customer": 5,
                "property_stock_supplier": 4,
                "property_supplier_payment_term_id": False,
                "prospect": False,
                "ref": False,
                "remarks_marketing": False,
                "return_certificate": False,
                "sale_warn": "no-message",
                "signature_for_reports": False,
                "signature_for_reports_fname": False,
                "state_id": False,
                "street": False,
                "street2": False,
                "student": False,
                "student_auth_identification": False,
                "student_auth_identification_fname": False,
                "student_auth_identification_id": False,
                "supplier_rank": 0,
                "teacher": False,
                "testimonial": False,
                "title": False,
                "training_plan": False,
                "training_plan_fname": False,
                "type": "private",
                "unmarried_name": False,
                "user_id": False,
                "vat": False,
                "website": False,
                "work_certificate": False,
                "work_certificate_fname": False,
                "zip": False,
            },
            # second sample set creating student with nearly everything empty
            {
                "__last_update": False,
                "academic_title": False,
                "active": True,
                "additional_info": False,
                "ahv_number": False,
                "assistant": False,
                "bfs_before_study_id": False,
                "bfs_school_code": False,
                "bfs_student_auth_id_code": False,
                "birthdate": False,
                "category_id": [[6, False, []]],
                "certification_date_before": 0,
                "city": False,
                "collaborator_ce": False,
                "comment": False,
                "company_id": False,
                "company_name": False,
                "company_type": "person",
                "country_at_auth_identification": False,
                "country_id": False,
                "country_now": False,
                "cover_letter": False,
                "cover_letter_fname": False,
                "customer_rank": 0,
                "cv_file": False,
                "cv_file_fname": False,
                "date_marketing": False,
                "diplomas_file": False,
                "diplomas_file_fname": False,
                "email": False,
                "employee": False,
                "enable_contact_data": False,
                "expenses_remarks": False,
                "fields_visible": False,
                "first_name_for_reports": False,
                "for_matri_number": False,
                "foreign_school": False,
                "function": False,
                "function2_id": False,
                "function_id": False,
                "gender": False,
                "id_cas_file": False,
                "id_cas_file_fname": False,
                "identity_card": False,
                "identity_card_fname": False,
                "image_1920": False,
                "inactive_teacher": False,
                "industry_id": False,
                "invoice_warn": "no-message",
                "invoice_with_post": False,
                "is_company": False,
                "lang": "en_US",
                "last_name": "Ho",
                "last_name_for_reports": False,
                "link_cv": False,
                "matriculation_number": False,
                "mentoren_tutoren": False,
                "message_attachment_count": 0,
                "mobile": False,
                "moodle_id": 0,
                "moodle_pending_discharge": False,
                "moodle_pending_enrollment": False,
                "moodle_synced": False,
                "name": "Hugo",
                "other": False,
                "parent_id": False,
                "partner_gid": 0,
                "phone": False,
                "photo1": False,
                "photo2": False,
                "photo3": False,
                "picking_warn": "no-message",
                "profession": False,
                "property_account_payable_id": 13,
                "property_account_position_id": False,
                "property_account_receivable_id": 6,
                "property_payment_term_id": False,
                "property_stock_customer": 5,
                "property_stock_supplier": 4,
                "property_supplier_payment_term_id": False,
                "prospect": False,
                "ref": False,
                "remarks_marketing": False,
                "return_certificate": False,
                "sale_warn": "no-message",
                "signature_for_reports": False,
                "signature_for_reports_fname": False,
                "state_id": False,
                "street": False,
                "street2": False,
                "student": False,
                "student_auth_identification": False,
                "student_auth_identification_fname": False,
                "student_auth_identification_id": False,
                "supplier_rank": 0,
                "teacher": False,
                "testimonial": False,
                "title": False,
                "training_plan": False,
                "training_plan_fname": False,
                "type": "private",
                "unmarried_name": False,
                "user_id": False,
                "vat": False,
                "website": False,
                "work_certificate": False,
                "work_certificate_fname": False,
                "zip": False,
            },
        ],
    },
    "semester": {
        "module": "semester",
        "search" : ["year", "type"], # do not create, when object is found using these elements
        # creating a semester()
        "vals_list": [
            {
                "active": True,
                "name": "Sommersemester 2020",
                "short_name": "SS20",
                "type": "2",
                "year": 2020,
            },
            {
                "active": True,
                "name": "Wintersemester 2021",
                "short_name": "ws2021",
                "type": "4",
                "year": 2021,
            },
        ],
    },
    # Create: Price event for unknown student
    # self product.product()
    "price_event": {
        "module": "product.product",
        "search" : ["name",], # do not create, when object is found using these elements
        "vals_list": [
            {
                "__last_update": False,
                "active": True,
                "barcode": False,
                "can_be_expensed": False,
                "categ_id": 1,
                "company_id": False,
                "default_code": "201",
                "description": False,
                "description_picking": False,
                "description_pickingin": False,
                "description_pickingout": False,
                "description_sale": False,
                "expense_policy": "no",
                "image_1920": False,
                "invoice_policy": "order",
                "lst_price": 170,
                "message_attachment_count": 0,
                "name": "Teilnahme Präsenzveranstaltung",
                "property_account_expense_id": False,
                "property_account_income_id": False,
                "property_stock_inventory": 14,
                "property_stock_production": 15,
                "purchase_ok": False,
                "route_ids": [[6, False, []]],
                "sale_delay": 0,
                "sale_line_warn": "no-message",
                "sale_ok": True,
                "service_type": "manual",
                "supplier_taxes_id": [[6, False, [2]]],
                "taxes_id": [[6, False, []]],
                #"tic_category_id": False,
                "tracking": "none",
                "type": "service",
                "uom_id": 1,
                "uom_po_id": 1,
                "volume": 0,
                "weight": 0,
            },
            # Create: Price Holyday
            # self product.product()
            {
                "__last_update": False,
                "active": True,
                "barcode": False,
                "can_be_expensed": False,
                "categ_id": 1,
                "company_id": False,
                "default_code": "113",
                "description": False,
                "description_picking": False,
                "description_pickingin": False,
                "description_pickingout": False,
                "description_sale": False,
                "expense_policy": "no",
                "image_1920": False,
                "invoice_policy": "order",
                "lst_price": 200,
                "message_attachment_count": 0,
                "name": "Urlaubsgebühr Bachelor",
                "property_account_expense_id": False,
                "property_account_income_id": False,
                "property_stock_inventory": 14,
                "property_stock_production": 15,
                "purchase_ok": False,
                "route_ids": [[6, False, []]],
                "sale_delay": 0,
                "sale_line_warn": "no-message",
                "sale_ok": True,
                "service_type": "manual",
                "supplier_taxes_id": [[6, False, [2]]],
                "taxes_id": [[6, False, []]],
                #"tic_category_id": False,
                "tracking": "none",
                "type": "service",
                "uom_id": 1,
                "uom_po_id": 1,
                "volume": 0,
                "weight": 0,
            },
            # Create: Create: Price Part Time
            # self product.product()
            {
                "__last_update": False,
                "active": True,
                "barcode": False,
                "can_be_expensed": False,
                "categ_id": 1,
                "company_id": False,
                "default_code": "111",
                "description": False,
                "description_picking": False,
                "description_pickingin": False,
                "description_pickingout": False,
                "description_sale": False,
                "expense_policy": "no",
                "image_1920": False,
                "invoice_policy": "order",
                "lst_price": 1300,
                "message_attachment_count": 0,
                "name": "Semestergebühr Bachelor",
                "property_account_expense_id": False,
                "property_account_income_id": False,
                "property_stock_inventory": 14,
                "property_stock_production": 15,
                "purchase_ok": True,
                "route_ids": [[6, False, []]],
                "sale_delay": 0,
                "sale_line_warn": "no-message",
                "sale_ok": True,
                "service_type": "manual",
                "supplier_taxes_id": [[6, False, [2]]],
                "taxes_id": [[6, False, []]],
                #"tic_category_id": False,
                "tracking": "none",
                "type": "service",
                "uom_id": 1,
                "uom_po_id": 1,
                "volume": 0,
                "weight": 0,
            },
        ],
    },
    # -------- creation of university
    "university": {
        "module": "university",
        "search" : ["name",], # do not create, when object is found using these elements
        "vals_list": [
            {
                "active": True,
                "name": "Universitäre Fernstudien Schweiz",
                "price_event_unknown_student_id": ('product.product', [('name', 'Teilnahme Präsenzveranstaltung')]), #43,
                "pud": False,
                "puf": False,
            }
        ],
    },
    # -------->>>>>>>>>>> Missing Create: Cost Center
    # -------- Create: Study Center
    "study_center": {
        "module": "study.center",
        "search" : ["name",], # do not create, when object is found using these elements
        "vals_list": [
            {
                "active": True,
                "address0": False,
                "address1": False,
                "address2": False,
                "address3": False,
                "address4": False,
                "city": "Brig",
                "e_mail": "studentservices@fernuni.ch",
                "name": "Forschung und Entwicklung",
                "phone": "+41 840 840 820",
                "secretary_user_id": False,
                "short_name": "Forschung und Entwicklung",
                "user_id": ('res.users', [('login', 'manuela')]), #24,
                "webseite": "http://fernuni.ch/ueber-uns/organisation/standorte/pfaeffikon-sz/",
            }
        ],
    },
    # -------- Create: Study course
    "study_course": {
        "module": "study.course",
        "search" : ["certificate",], # do not create, when object is found using these elements
        "vals_list": [{'access_further_studies_de': False,
            'access_further_studies_en': False,
            'access_further_studies_fr': False,
            'access_requirements_de': False,
            'access_requirements_en': False,
            'access_requirements_fr': False,
            'active': True,
            'additional_documents_online_registration': False,
            'bfs_number': 0,
            'blocking_semester_ids': [[6, False, []]],
            'canadian_credits': 0,
            'certificate': 'Bachelor of Science in Psychology',
            'compensation': False,
            'coordination': False,
            'cost_center': 1,
            'date_of_introduction_session': False,
            'dekan': False,
            'department_id': 1,
            'ects': 180,
            'english': False,
            'final_degree_short_name': 'B Sc',
            'french': False,
            'german': False,
            'grade_id': 2,
            'guest': False,
            'ignore_sis_import': False,
            'introduction_session_place': False,
            'is_dekansalaryrelevant': True,
            'iuv_group': False,
            'language_de': False,
            'language_en': False,
            'language_fr': False,
            'level_qualification_de': False,
            'level_qualification_en': False,
            'level_qualification_fr': False,
            'main_de': False,
            'main_en': False,
            'main_fr': False,
            'max_failed_tries': False,
            'max_study_duration': 0,
            'mode_study_de': False,
            'mode_study_en': False,
            'mode_study_fr': False,
            'modules_students': True,
            'moodle_general_courses': False,
            'name': 'Bachelor of Science in Psychology',
            'offical_length_worlkload_de': False,
            'offical_length_worlkload_en': False,
            'offical_length_worlkload_fr': False,
            'price_application': False,
            'price_holiday': False,
            'price_module': False,
            'price_program': False,
            'professional_status_de': False,
            'professional_status_en': False,
            'professional_status_fr': False,
            'programme_requirements_de': False,
            'programme_requirements_en': False,
            'programme_requirements_fr': False,
            'remarks': False,
            'semesters_full_time': 0,
            'semesters_part_time': 0,
            'short_name': 'B Sc in Psychology',
            'student_resources_type_ids': [[6, False, []]],
            'study_center_id': 2,
            'study_course_code': 'BSCPSYd',
            'study_course_mail': 'studentservices@fernuni.ch',
            'study_course_phone': '0840 840 820',
            'study_course_url': False,
            'study_goal': 'Bachelor of Science',
            'subject_study': 'Psychologie',
            'training_course': False,
            'university_id': 1,
            'visible_online_registration': True,
            'weiterbildung': False,
            'workgroup_ids': [[6, False, []]]}]
,
    },
    # -------->>>>>>>>>>> Create: Create: Department
    "department": {
        "module": "department",
        "search" : ["name",], # do not create, when object is found using these elements
        "vals_list": [
            {
                "active": True,
                "faculty_manager_id": 62,
                "french": False,
                "german": True,
                "name": "Rechtswissenschaften",
                "short_name": "LAWd",
            }
        ],
    },
    # -------- Create: Grade
    "grade": {
        "module": "grade",
        "search" : ["name",], # do not create, when object is found using these elements
        "vals_list": [
            {"active": True, "bfs_grade_code": 25, "name": "Master"},
            {'active': True, 'bfs_grade_code': 15, 'name': 'Bachelor'}
        ],
    },
    # -------- Create: Reason Exmatriculation
    "reason_exmatriculation": {
        "module": "reason.exmatriculation",
        "search" : ["name",], # do not create, when object is found using these elements
        "vals_list": [
            {
                "calc_predicate_final_grade": False,
                "manual_signature": False,
                "name": "Exmatrikulation auf studentisches Begehren",
                "text": False,
                "text_report": False,
            }
        ],
    },
    # -------- Create: studies
    "studies": {
        "module": "studies",
        "search" : ["partner_id",], # do not create, when object is found using these elements
        "vals_list": [
            {
                "abandon": False,
                "accept_conditions": False,
                "annee_academique": False,
                "approval_exmatriculation": False,
                "approve_first_section": False,
                "continuing_education": False,
                "created_email": False,
                "created_moodle_account": False,
                "credit_application_available": False,
                "date": False,
                "date_end": 2,
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": 1,
                "decision": False,
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "finished_immatriculations": False,
                "geburtsort": False,
                "guest": False,
                "horerstatus": False,
                "kohorte_id": False,
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ('res.partner', [('name', 'Student'), ('last_name', 'Fleissig')]), #70,
                "permission_date": False,
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                "reason_exmatriculation": 1,
                "remarks_credit_application": False,
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                "study_course_id": False,
                "total_ects_credits": 0,
                "valid_information": False,
                "validation_acquis": False,
            }
        ],
    },
    # -------- Create: kohorte
    "kohorte": {
        "module": "kohorte",
        "vals_list": [{"name": "K28", "semester_id": 1, "study_course_id": 1}],
    },
    # create account.analytic.account
    'account_analytic_account' : {
        "module": "account.analytic.account",
        "search" : ["code",],
        "login" : "admin",
        "vals_list" : [{'active': True,
        'code': 'BPSYd',
        'company_id': 1,
        'group_id': False,
        'message_attachment_count': 0,
        'message_follower_ids': [(0,
                                    0,
                                    {'partner_id': 22,
                                    'res_model': 'account.analytic.account',
                                    'subtype_ids': [(6, 0, [1])]})],
        'name': 'Bachelor Psychologie d',
        'partner_id': False}]
    }
}
