# # ----------------------------------------------------------------------------
# # creating trough odoo
# # ----------------------------------------------------------------------------
# vals = {'calendar_last_notif_ack': datetime.datetime(2019, 11, 16, 16, 59, 15),
#  'category_id': [(6, 0, [])],
#  'color': 0,
#  'customer_rank': 0,
#  'email': False,
#  'image_1920': False,
#  'invoice_warn': 'no-message',
#  'is_company': False,
#  'is_sekretariat_or_higher': False,
#  'lang': 'en_US',
#  'last_name': 'Moldenhauer',
#  'last_semester': 0,
#  'message_bounce': 0,
#  'name': 'Rottermann Moldenhauer',
#  'picking_warn': 'no-message',
#  'property_account_payable_id': 13,
#  'property_account_position_id': False,
#  'property_account_receivable_id': 6,
#  'property_payment_term_id': False,
#  'property_stock_customer': 5,
#  'property_stock_supplier': 4,
#  'property_supplier_payment_term_id': False,
#  'prospect': False,
#  'sale_warn': 'no-message',
#  'supplier_rank': 0,
#  'trust': 'normal',
#  'type': 'contact',
#  'tz': 'Europe/Brussels'}

# vals_list = [{'calendar_last_notif_ack': datetime.datetime(2019, 11, 16, 17, 10, 51),
#   'category_id': [(6, 0, [])],
#   'color': 0,
#   'customer_rank': 0,
#   'email': False,
#   'image_1920': False,
#   'invoice_warn': 'no-message',
#   'is_company': False,
#   'is_sekretariat_or_higher': False,
#   'lang': 'en_US',
#   'last_name': 'Moldenhauer',
#   'last_semester': 0,
#   'message_bounce': 0,
#   'message_follower_ids': [(0,
#                             0,
#                             {'partner_id': 3,
#                              'res_model': 'res.partner',
#                              'subtype_ids': [(6, 0, [1])]})],
#   'name': 'Rottermann Moldenhauer',
#   'picking_warn': 'no-message',
#   'property_account_payable_id': 13,
#   'property_account_position_id': False,
#   'property_account_receivable_id': 6,
#   'property_payment_term_id': False,
#   'property_stock_customer': 5,
#   'property_stock_supplier': 4,
#   'property_supplier_payment_term_id': False,
#   'prospect': False,
#   'sale_warn': 'no-message',
#   'supplier_rank': 0,
#   'trust': 'normal',
#   'type': 'contact',
#   'tz': 'Europe/Brussels'}]
# # ----------------------------------------------------------------------------
# # end creating trough odoo
# # ----------------------------------------------------------------------------


# creating a student:
# self ->res.partner()
vals = {
 '__last_update': False,
 'academic_title': False,
 'active': True,
 'additional_info': False,
 'ahv_number': '999.9999.9999.99',
 'assistant': False,
 'bfs_before_study_id': False,
 'bfs_school_code': False,
 'bfs_student_auth_id_code': False,
 'birthdate': '1999-01-05',
 'certification_date_before': 0,
 'city': False,
 'collaborator_ce': False,
 'comment': False,
 'company_id': False,
 'company_name': False,
 'country_at_auth_identification': False,
 'country_id': False,
 'country_now': False,
 'cover_letter': False,
 'cover_letter_fname': False,
 'customer_rank': 0,
 'cv_file': False,
 'cv_file_fname': False,
 'date_marketing': False,
 'diplomas_file': False,
 'diplomas_file_fname': False,
 'employee': False,
 'enable_contact_data': False,
 'expenses_remarks': False,
 'fields_visible': False,
 'first_name_for_reports': False,
 'for_matri_number': False,
 'foreign_school': False,
 'function': False,
 'function2_id': False,
 'function_id': False,
 'gender': '1',
 'id_cas_file': False,
 'id_cas_file_fname': False,
 'identity_card': False,
 'identity_card_fname': False,
 'image_1920': False,
 'inactive_teacher': False,
 'industry_id': False,
 'invoice_warn': 'no-message',
 'invoice_with_post': False,
 'is_company': False,
 'lang': 'de_CH',
 'last_name': 'Fleissig',
 'last_name_for_reports': False,
 'link_cv': False,
 'matriculation_number': False,
 'mentoren_tutoren': False,
 'message_attachment_count': 0,
 'mobile': False,
 'moodle_id': 0,
 'moodle_pending_discharge': False,
 'moodle_pending_enrollment': False,
 'moodle_synced': False,
 'name': 'Student',
 'other': False,
 'partner_gid': 0,
 'phone': False,
 'photo1': False,
 'photo2': False,
 'photo3': False,
 'picking_warn': 'no-message',
 'profession': False,
 'property_account_payable_id': 13,
 'property_account_position_id': False,
 'property_account_receivable_id': 6,
 'property_payment_term_id': False,
 'property_stock_customer': 5,
 'property_stock_supplier': 4,
 'property_supplier_payment_term_id': False,
 'prospect': False,
 'ref': False,
 'remarks_marketing': False,
 'return_certificate': False,
 'sale_warn': 'no-message',
 'signature_for_reports': False,
 'signature_for_reports_fname': False,
 'state_id': False,
 'street': False,
 'street2': False,
 'student': False,
 'student_auth_identification': False,
 'student_auth_identification_fname': False,
 'student_auth_identification_id': False,
 'supplier_rank': 0,
 'teacher': False,
 'testimonial': False,
 'title': False,
 'training_plan': False,
 'training_plan_fname': False,
 'type': 'private',
 'unmarried_name': False,
 'user_id': False,
 'vat': False,
 'website': False,
 'work_certificate': False,
 'work_certificate_fname': False,
 'zip': False}

# self semester()
vals = {'active': True,
 'name': 'Sommersemester 2020',
 'short_name': 'SS20',
 'type': '2',
 'year': 2020}

# self semester()
vals = {
 'active': True,
 'name': 'Wintersemester 2021',
 'short_name': 'ws2021',
 'type': '4',
 'year': 2021}

# Create: Price event for unknown student
# self product.product()
vals_list = [
{'__last_update': False,
  'active': True,
  'barcode': False,
  'can_be_expensed': False,
  'categ_id': 1,
  'company_id': False,
  'default_code': '201',
  'description': False,
  'description_picking': False,
  'description_pickingin': False,
  'description_pickingout': False,
  'description_sale': False,
  'expense_policy': 'no',
  'image_1920': False,
  'invoice_policy': 'order',
  'lst_price': 170,
  'message_attachment_count': 0,
  'name': 'Teilnahme Präsenzveranstaltung',
  'property_account_expense_id': False,
  'property_account_income_id': False,
  'property_stock_inventory': 14,
  'property_stock_production': 15,
  'purchase_ok': False,
  'route_ids': [[6, False, []]],
  'sale_delay': 0,
  'sale_line_warn': 'no-message',
  'sale_ok': True,
  'service_type': 'manual',
  'supplier_taxes_id': [[6, False, [2]]],
  'taxes_id': [[6, False, []]],
  'tic_category_id': False,
  'tracking': 'none',
  'type': 'service',
  'uom_id': 1,
  'uom_po_id': 1,
  'volume': 0,
  'weight': 0}]

# -------->>>>>>>>>>> Missing creation of university
# -------->>>>>>>>>>> Missing Create: Cost Center
# -------->>>>>>>>>>> Missing Create: Study Center
# -------->>>>>>>>>>> Missing Create: Create: Department
# -------->>>>>>>>>>> Missing Create: Grade

# Create: Price Holyday
# self product.product()
vals_list [{'__last_update': False,
  'active': True,
  'barcode': False,
  'can_be_expensed': False,
  'categ_id': 1,
  'company_id': False,
  'default_code': '113',
  'description': False,
  'description_picking': False,
  'description_pickingin': False,
  'description_pickingout': False,
  'description_sale': False,
  'expense_policy': 'no',
  'image_1920': False,
  'invoice_policy': 'order',
  'lst_price': 200,
  'message_attachment_count': 0,
  'name': 'Urlaubsgebühr Bachelor',
  'property_account_expense_id': False,
  'property_account_income_id': False,
  'property_stock_inventory': 14,
  'property_stock_production': 15,
  'purchase_ok': False,
  'route_ids': [[6, False, []]],
  'sale_delay': 0,
  'sale_line_warn': 'no-message',
  'sale_ok': True,
  'service_type': 'manual',
  'supplier_taxes_id': [[6, False, [2]]],
  'taxes_id': [[6, False, []]],
  'tic_category_id': False,
  'tracking': 'none',
  'type': 'service',
  'uom_id': 1,
  'uom_po_id': 1,
  'volume': 0,
  'weight': 0}]

# Create: Create: Price Part Time
# self product.product()
vals_list = [{'__last_update': False,
  'active': True,
  'barcode': False,
  'can_be_expensed': False,
  'categ_id': 1,
  'company_id': False,
  'default_code': '111',
  'description': False,
  'description_picking': False,
  'description_pickingin': False,
  'description_pickingout': False,
  'description_sale': False,
  'expense_policy': 'no',
  'image_1920': False,
  'invoice_policy': 'order',
  'lst_price': 1300,
  'message_attachment_count': 0,
  'name': 'Semestergebühr Bachelor',
  'property_account_expense_id': False,
  'property_account_income_id': False,
  'property_stock_inventory': 14,
  'property_stock_production': 15,
  'purchase_ok': True,
  'route_ids': [[6, False, []]],
  'sale_delay': 0,
  'sale_line_warn': 'no-message',
  'sale_ok': True,
  'service_type': 'manual',
  'supplier_taxes_id': [[6, False, [2]]],
  'taxes_id': [[6, False, []]],
  'tic_category_id': False,
  'tracking': 'none',
  'type': 'service',
  'uom_id': 1,
  'uom_po_id': 1,
  'volume': 0,
  'weight': 0}]
# -------->>>>>>>>>>> Missing  Create: Reason Exmatriculation
