# # ----------------------------------------------------------------------------
# # creating trough odoo
# # ----------------------------------------------------------------------------
# vals = {'calendar_last_notif_ack': datetime.datetime(2019, 11, 16, 16, 59, 15),
#  'category_id': [(6, 0, [])],
#  'color': 0,
#  'customer_rank': 0,
#  'email': False,
#  'image_1920': False,
#  'invoice_warn': 'no-message',
#  'is_company': False,
#  'is_sekretariat_or_higher': False,
#  'lang': 'en_US',
#  'last_name': 'Moldenhauer',
#  'last_semester': 0,
#  'message_bounce': 0,
#  'name': 'Rottermann Moldenhauer',
#  'picking_warn': 'no-message',
#  'property_account_payable_id': 13,
#  'property_account_position_id': False,
#  'property_account_receivable_id': 6,
#  'property_payment_term_id': False,
#  'property_stock_customer': 5,
#  'property_stock_supplier': 4,
#  'property_supplier_payment_term_id': False,
#  'prospect': False,
#  'sale_warn': 'no-message',
#  'supplier_rank': 0,
#  'trust': 'normal',
#  'type': 'contact',
#  'tz': 'Europe/Brussels'}

# vals_list = [{'calendar_last_notif_ack': datetime.datetime(2019, 11, 16, 17, 10, 51),
#   'category_id': [(6, 0, [])],
#   'color': 0,
#   'customer_rank': 0,
#   'email': False,
#   'image_1920': False,
#   'invoice_warn': 'no-message',
#   'is_company': False,
#   'is_sekretariat_or_higher': False,
#   'lang': 'en_US',
#   'last_name': 'Moldenhauer',
#   'last_semester': 0,
#   'message_bounce': 0,
#   'message_follower_ids': [(0,
#                             0,
#                             {'partner_id': 3,
#                              'res_model': 'res.partner',
#                              'subtype_ids': [(6, 0, [1])]})],
#   'name': 'Rottermann Moldenhauer',
#   'picking_warn': 'no-message',
#   'property_account_payable_id': 13,
#   'property_account_position_id': False,
#   'property_account_receivable_id': 6,
#   'property_payment_term_id': False,
#   'property_stock_customer': 5,
#   'property_stock_supplier': 4,
#   'property_supplier_payment_term_id': False,
#   'prospect': False,
#   'sale_warn': 'no-message',
#   'supplier_rank': 0,
#   'trust': 'normal',
#   'type': 'contact',
#   'tz': 'Europe/Brussels'}]
# # ----------------------------------------------------------------------------
# # end creating trough odoo
# # ----------------------------------------------------------------------------
