#!/usr/bin/env python
# # -*- coding: utf-8 -*-
from odoo_handler import get_objects
sample_data = {
    "room" : {
        "module" : "room",
        "search": ['name', 'location_id'],
        "vals_list": [
            {
                'active': True,
                'location_id': ("location", [("short_name", "PHBE IS1")]),
                'name': 'Hörraum 004',
                'number_seats': 65,
                'remarks': 'Beamer, OHP',
                'room_plan': False,
                'room_plan_fname': False
            }
        ]
    },
}


holidays()
vals_list
[{'full_part_time_id': False,
  'number_of_semesters': '1',
  'reason': '3',
  'remarks': False,
  'semester_id': 21,
  'studies_id': 6,
  'type': 'holiday'}]

[{'full_part_time_id': False,
  'number_of_semesters': '1',
  'reason': '3',
  'remarks': False,
  'semester_id': 22,
  'studies_id': 6,
  'type': 'holiday'}]

self
student.semester()
vals_list
[{'automatically_created': True,
  'choose_student_module_finished': True,
  'part_time': True,
  'semester_id': 22,
  'state_student_semester': '2',
  'studies_id': 6}]


account.move()

vals_list
[{'asset_id': False,
  'auto_post': False,
  'campaign_id': False,
  'currency_id': 5,
  'date': '2020-01-27',
  'ects_credits': 100,
  'external_invoice_number': False,
  'extract_state': 'no_extract_requested',
  'extract_status_code': 0,
  'fiscal_position_id': False,
  'internal_comment': False,
  'invoice_cash_rounding_id': False,
  'invoice_date': '2020-01-27',
  'invoice_date_due': '2020-02-11',
  'invoice_incoterm_id': False,
  'invoice_partner_bank_id': False,
  'invoice_payment_ref': False,
  'invoice_payment_state': 'not_paid',
  'invoice_payment_term_id': 2,
  'invoice_sequence_number_next': '0001',
  'invoice_source_email': False,
  'invoice_user_id': 1,
  'invoice_vendor_bill_id': False,
  'is_tax_closing': False,
  'journal_id': 1,
  'l10n_ch_isr_sent': False,
  'line_ids': [[0,
                'virtual_319',
                {'account_id': 104,
                 'amount_currency': 0,
                 'analytic_account_id': False,
                 'analytic_tag_ids': [[6, False, []]],
                 'credit': 200,
                 'currency_id': False,
                 'date_maturity': False,
                 'debit': 0,
                 'discount': 0,
                 'display_type': False,
                 'exclude_from_invoice_tab': False,
                 'is_rounding_line': False,
                 'name': '[113] Urlaubsgebühr Bachelor',
                 'partner_id': 50,
                 'payment_id': False,
                 'predict_from_name': False,
                 'predict_override_default_account': True,
                 'price_unit': 200,
                 'product_id': 2,
                 'product_uom_id': 1,
                 'quantity': 1,
                 'recompute_tax_line': False,
                 'sequence': 10,
                 'tag_ids': [[6, False, [17]]],
                 'tax_base_amount': 0,
                 'tax_exigible': True,
                 'tax_ids': [[6, False, [13]]],
                 'tax_repartition_line_id': False}],
               [0,
                'virtual_344',
                {'account_id': 76,
                 'amount_currency': 0,
                 'analytic_account_id': False,
                 'analytic_tag_ids': [[6, False, []]],
                 'credit': 15.4,
                 'currency_id': False,
                 'date_maturity': False,
                 'debit': 0,
                 'discount': 0,
                 'display_type': False,
                 'exclude_from_invoice_tab': True,
                 'is_rounding_line': False,
                 'name': 'TVA due a 7.7% (TN)',
                 'partner_id': 50,
                 'payment_id': False,
                 'predict_from_name': False,
                 'predict_override_default_account': False,
                 'price_unit': 15.4,
                 'product_id': False,
                 'product_uom_id': False,
                 'quantity': 1,
                 'recompute_tax_line': False,
                 'sequence': 10,
                 'tag_ids': [[6, False, [27]]],
                 'tax_base_amount': 200,
                 'tax_exigible': True,
                 'tax_ids': [[6, False, []]],
                 'tax_repartition_line_id': 26}],
               [0,
                'virtual_355',
                {'account_id': 6,
                 'amount_currency': 0,
                 'analytic_account_id': False,
                 'analytic_tag_ids': [[6, False, []]],
                 'credit': 0,
                 'currency_id': False,
                 'date_maturity': '2020-02-11',
                 'debit': 215.4,
                 'discount': 0,
                 'display_type': False,
                 'exclude_from_invoice_tab': True,
                 'is_rounding_line': False,
                 'name': False,
                 'partner_id': 50,
                 'payment_id': False,
                 'predict_from_name': False,
                 'predict_override_default_account': False,
                 'price_unit': -215.4,
                 'product_id': False,
                 'product_uom_id': False,
                 'quantity': 1,
                 'recompute_tax_line': False,
                 'sequence': 10,
                 'tag_ids': [[6, False, []]],
                 'tax_base_amount': 0,
                 'tax_exigible': True,
                 'tax_ids': [[6, False, []]],
                 'tax_repartition_line_id': False}]],
  'medium_id': False,
  'message_attachment_count': 0,
  'message_follower_ids': [(0,
                            0,
                            {'partner_id': 2,
                             'res_model': 'account.move',
                             'subtype_ids': [(6, 0, [1])]})],
  'message_main_attachment_id': False,
  'narration': False,
  'partner_id': 50,
  'partner_shipping_id': 50,
  'print_state': 'not_print',
  'ref': False,
  'semester_id': 18,
  'semester_number': '1',
  'source_id': False,
  'study_course_id': 5,
  'tax_report_control_error': False,
  'team_id': 1,
  'to_check': False}]
