#!/usr/bin/env python
# -*- coding: utf-8 -*-
from odoo_handler import get_objects, get_students
sample_data = {
    "module_data": {
        "module": "module.data",
        "search": [
            "short_name",
            "semester_id",
            "module_number",
        ],  # do not create, when object is found using these elements
        "has_data_file": True,
        "step": "second_run",
        "vals_list": [
            {
                "active": True,
                "choose_student_module": False,
                "content_of_study": False,
                "dependency_finished_ids": [[6, False, []]],
                "dependency_ids": [[6, False, []]],
                "description": False,
                "dummy": False,
                "ect_credist": 10,
                "enable_module": False,
                "group": "2",
                "guest": False,
                "kohorte_ids": [[6, False, []]],
                "learning_outcomes": False,
                "message_attachment_count": 0,
                "module_code": 'STAAT',
                "module_id": ("module", [("module_code", "EINF"), ('module_number', 'M03')]), #1,,
                "module_number": 'M03',
                "modules_students": True,
                "moodle_id": 0,
                "name": "Allgemeine Staatslehre",
                "publish_on_website": False,
                "repetition": "3", #spring and autumn semester
                "requirements": False,
                "semester": 1,
                "semester_id": ("semester", [("short_name", "FS20")]),
                "short_name": "Allgemeine Staatslehre",
                "study_course_ids": [
                    [6, False, get_objects("study.course", login=["matthias", "login"])]
                ],
                "study_section_id": ("study.section",
                    [("name", "1. Teil"),('study_course_id', ("study.course", [("study_course_code", "BLAWd")]))]), #1, # SUCHEN!!
                "survey_cas_question_ids": [[6, False, []]],
                "survey_specific_question_ids": [[6, False, []]],
                "teaching_material": False,
                "type": '1', # Wat is that pfichtfach
                "type_of_exam": "exam",
                "validation_state": "not_validated",
                "number_of_events_to_visit": "3",
            },
        ],
        # we use vals_list_data to "fill" the valslist with real data
        "vals_list_data": [
            {'ect_credist': 10,
            'group': '2',
            'guest': False,
            'kohorte_ids': [[6, False, []]],
            'module_code': 'ARB',
            'module_id': ('module', [('module_code', 'ARB'), ('module_number', 'M17')]),
            'module_number': 'M17',
            'moodle_id': 343,
            'name': 'Arbeitspsychologie – Organisationspsychologie',
            'number_of_events_to_visit': '3',
            'repetition': '3',
            'semester': 9,
            'semester_id': ('semester', [('short_name', 'FS16')]),
            'short_name': 'Arbeitspsychologie – Organisationspsychologie',
            'study_course_ids': [[6, False, [1, 2, 3, 4, 5, 6, 7, 8]]],
            'study_section_id': ('study.section',
                                [('name', '2. Studienabschnitt'),
                                ('study_course_id',
                                    ('study.course', [('study_course_code', 'BSCPSYd')]))]),
            'type': '1',
            'type_of_exam': 'exam',
            'validation_state': 'not_validated'},
            {'ect_credist': 10,
            'group': '2',
            'guest': False,
            'kohorte_ids': [[6, False, []]],
            'module_code': 'STAAT',
            'module_id': ('module', [('module_code', 'STAAT'), ('module_number', 'M03')]),
            'module_number': 'M03',
            'moodle_id': 0,
            'name': 'Allgemeine Staatslehre',
            'number_of_events_to_visit': '3',
            'repetition': '3',
            'semester': 1,
            'semester_id': ('semester', [('short_name', 'FS20')]),
            'short_name': 'Allgemeine Staatslehre',
            'study_course_ids': [[6, False, [1, 2, 3, 4, 5, 6, 7, 8]]],
            'study_section_id': ('study.section',
                                [('name', '1. Teil'),
                                ('study_course_id',
                                    ('study.course', [('study_course_code', 'BLAWd')]))]),
            'type': '1',
            'type_of_exam': 'exam',
            'validation_state': 'not_validated'},
            {'ect_credist': 6,
            'group': '2',
            'guest': False,
            'kohorte_ids': [[6, False, []]],
            'module_code': 'SFSD',
            'module_id': ('module', [('module_code', 'SFSD'), ('module_number', 'M00')]),
            'module_number': 'M00',
            'moodle_id': 0,
            'name': 'Savoir-faire et savoir devenir',
            'number_of_events_to_visit': '3',
            'repetition': '3',
            'semester': 1,
            'semester_id': ('semester', [('short_name', 'FS18')]),
            'short_name': 'SF & SD',
            'study_course_ids': [[6, False, [1, 2, 3, 4, 5, 6, 7, 8]]],
            'study_section_id': ('study.section', [('name', 'Propédeutique')]),
            'type': '1',
            'type_of_exam': 'activity',
            'validation_state': 'not_validated'},
            {'ect_credist': 10,
            'group': '2',
            'guest': False,
            'kohorte_ids': [[6, False, []]],
            'module_code': 'Travail de Bachelor',
            'module_id': ('module',
                        [('module_number', 'M18'), ('name', 'Travail de Bachelor')]),
            'module_number': 'M18',
            'moodle_id': 1118,
            'name': 'Travail de Bachelor',
            'number_of_events_to_visit': '0',
            'repetition': '3',
            'semester': 9,
            'semester_id': ('semester', [('short_name', 'FS18')]),
            'short_name': 'Travail de Bachelor',
            'study_course_ids': [[6, False, [1, 2, 3, 4, 5, 6, 7, 8]]],
            'study_section_id': ('study.section', [('name', '2ème cycle')]),
            'type': '1',
            'type_of_exam': 'exam',
            'validation_state': 'not_validated'},
            {'ect_credist': 10,
            'group': '1',
            'guest': False,
            'kohorte_ids': [[6, False, []]],
            'module_code': 'ENTW',
            'module_id': ('module', [('module_code', 'ENTW'), ('module_number', 'M03')]),
            'module_number': 'M03',
            'moodle_id': 0,
            'name': 'Entwicklungspsychologie',
            'number_of_events_to_visit': '3',
            'repetition': '3',
            'semester': 2,
            'semester_id': ('semester', [('short_name', 'FS19')]),
            'short_name': 'Entwicklungspsychologie',
            'study_course_ids': [[6, False, [1, 2, 3, 4, 5, 6, 7, 8]]],
            'study_section_id': ('study.section',
                                [('name', '1. Teil'),
                                ('study_course_id',
                                    ('study.course', [('study_course_code', 'BSCPSYd')]))]),
            'type': '1',
            'type_of_exam': 'exam',
            'validation_state': 'not_validated'},
            {'ect_credist': 10,
            'group': '1',
            'guest': False,
            'kohorte_ids': [[6, False, []]],
            'module_code': 'EINF',
            'module_id': ('module', [('module_code', 'EINF'), ('module_number', 'M01')]),
            'module_number': 'M01',
            'moodle_id': 0,
            'name': 'Einführung in die Psychologie',
            'number_of_events_to_visit': '3',
            'repetition': '3',
            'semester': 1,
            'semester_id': ('semester', [('short_name', 'FS19')]),
            'short_name': 'Einführung in die Psychologie',
            'study_course_ids': [[6, False, [1, 2, 3, 4, 5, 6, 7, 8]]],
            'study_section_id': ('study.section',
                                [('name', '1. Teil'),
                                ('study_course_id',
                                    ('study.course', [('study_course_code', 'BSCPSYd')]))]),
            'type': '1',
            'type_of_exam': 'exam',
            'validation_state': 'not_validated'},
            {'ect_credist': 10,
            'group': '1',
            'guest': False,
            'kohorte_ids': [[6, False, []]],
            'module_code': 'STAT1',
            'module_id': ('module', [('module_code', 'STAT1'), ('module_number', 'M02')]),
            'module_number': 'M02',
            'moodle_id': 0,
            'name': 'Statistik I',
            'number_of_events_to_visit': '3',
            'repetition': '3',
            'semester': 1,
            'semester_id': ('semester', [('short_name', 'FS19')]),
            'short_name': 'Statistik I',
            'study_course_ids': [[6, False, [1, 2, 3, 4, 5, 6, 7, 8]]],
            'study_section_id': ('study.section',
                                [('name', '1. Teil'),
                                ('study_course_id',
                                    ('study.course', [('study_course_code', 'BSCPSYd')]))]),
            'type': '1',
            'type_of_exam': 'exam',
            'validation_state': 'not_validated'},
            {'ect_credist': 10,
            'group': '1',
            'guest': False,
            'kohorte_ids': [[6, False, []]],
            'module_code': 'ENTW',
            'module_id': ('module', [('module_code', 'ENTW'), ('module_number', 'M03')]),
            'module_number': 'M03',
            'moodle_id': 0,
            'name': 'Entwicklungspsychologie',
            'number_of_events_to_visit': '3',
            'repetition': '3',
            'semester': 2,
            'semester_id': ('semester', [('short_name', 'FS19')]),
            'short_name': 'Entwicklungspsychologie',
            'study_course_ids': [[6, False, [1, 2, 3, 4, 5, 6, 7, 8]]],
            'study_section_id': ('study.section',
                                [('name', '1. Teil'),
                                ('study_course_id',
                                    ('study.course', [('study_course_code', 'BSCPSYd')]))]),
            'type': '1',
            'type_of_exam': 'exam',
            'validation_state': 'not_validated'},
            {'ect_credist': 10,
            'group': '1',
            'guest': False,
            'kohorte_ids': [[6, False, []]],
            'module_code': 'STAT2',
            'module_id': ('module', [('module_code', 'STAT2'), ('module_number', 'M04')]),
            'module_number': 'M04',
            'moodle_id': 0,
            'name': 'Methoden II: Forschungsmethoden und Statistik II',
            'number_of_events_to_visit': '3',
            'repetition': '3',
            'semester': 2,
            'semester_id': ('semester', [('short_name', 'FS19')]),
            'short_name': 'Statistik II',
            'study_course_ids': [[6, False, [1, 2, 3, 4, 5, 6, 7, 8]]],
            'study_section_id': ('study.section',
                                [('name', '1. Teil'),
                                ('study_course_id',
                                    ('study.course', [('study_course_code', 'BSCPSYd')]))]),
            'type': '1',
            'type_of_exam': 'exam',
            'validation_state': 'not_validated'},
        ]
    },
}