#!/usr/bin/env python
# # -*- coding: utf-8 -*-
from odoo_handler import get_objects
sample_data = {
    # Create: Price event for unknown student
    # self product.product()
    "price_event": {
        "module": "product.product",
        "search": ["name"],  # do not create, when object is found using these elements
        "vals_list": [
            {
                "__last_update": False,
                "active": True,
                "barcode": False,
                "can_be_expensed": False,
                "categ_id": 1,
                "company_id": False,
                "default_code": "201",
                "description": False,
                "description_picking": False,
                "description_pickingin": False,
                "description_pickingout": False,
                "description_sale": False,
                "expense_policy": "no",
                "image_1920": False,
                "invoice_policy": "order",
                "lst_price": 170,
                "message_attachment_count": 0,
                "name": "Teilnahme Präsenzveranstaltung",
                "property_account_expense_id": False,
                "property_account_income_id": False,
                "property_stock_inventory": 14,
                "property_stock_production": 15,
                "purchase_ok": False,
                "route_ids": [[6, False, []]],
                "sale_delay": 0,
                "sale_line_warn": "no-message",
                "sale_ok": True,
                "service_type": "manual",
                "supplier_taxes_id": [[6, False, [2]]],
                "taxes_id": [[6, False, []]],
                # "tic_category_id": False,
                "tracking": "none",
                "type": "service",
                "uom_id": 1,
                "uom_po_id": 1,
                "volume": 0,
                "weight": 0,
            },
            # Create: Price Holyday
            # self product.product()
            {
                "__last_update": False,
                "active": True,
                "barcode": False,
                "can_be_expensed": False,
                "categ_id": 1,
                "company_id": False,
                "default_code": "113",
                "description": False,
                "description_picking": False,
                "description_pickingin": False,
                "description_pickingout": False,
                "description_sale": False,
                "expense_policy": "no",
                "image_1920": False,
                "invoice_policy": "order",
                "lst_price": 200,
                "message_attachment_count": 0,
                "name": "Urlaubsgebühr Bachelor",
                "property_account_expense_id": False,
                "property_account_income_id": False,
                "property_stock_inventory": 14,
                "property_stock_production": 15,
                "purchase_ok": False,
                "route_ids": [[6, False, []]],
                "sale_delay": 0,
                "sale_line_warn": "no-message",
                "sale_ok": True,
                "service_type": "manual",
                "supplier_taxes_id": [[6, False, [2]]],
                "taxes_id": [[6, False, []]],
                # "tic_category_id": False,
                "tracking": "none",
                "type": "service",
                "uom_id": 1,
                "uom_po_id": 1,
                "volume": 0,
                "weight": 0,
            },
            # Create: Create: Price Part Time
            # self product.product()
            {
                "__last_update": False,
                "active": True,
                "barcode": False,
                "can_be_expensed": False,
                "categ_id": 1,
                "company_id": False,
                "default_code": "111",
                "description": False,
                "description_picking": False,
                "description_pickingin": False,
                "description_pickingout": False,
                "description_sale": False,
                "expense_policy": "no",
                "image_1920": False,
                "invoice_policy": "order",
                "lst_price": 1300,
                "message_attachment_count": 0,
                "name": "Semestergebühr Bachelor",
                "property_account_expense_id": False,
                "property_account_income_id": False,
                "property_stock_inventory": 14,
                "property_stock_production": 15,
                "purchase_ok": True,
                "route_ids": [[6, False, []]],
                "sale_delay": 0,
                "sale_line_warn": "no-message",
                "sale_ok": True,
                "service_type": "manual",
                "supplier_taxes_id": [[6, False, [2]]],
                "taxes_id": [[6, False, []]],
                # "tic_category_id": False,
                "tracking": "none",
                "type": "service",
                "uom_id": 1,
                "uom_po_id": 1,
                "volume": 0,
                "weight": 0,
            },
            {
                "active": True,
                "barcode": False,
                "can_be_expensed": False,
                "categ_id": 1,
                "company_id": False,
                "default_code": "129",
                "description": False,
                "description_picking": False,
                "description_pickingin": False,
                "description_pickingout": False,
                "description_sale": False,
                "expense_policy": "no",
                "image_1920": False,
                "invoice_policy": "order",
                "lst_price": 1300,
                "message_attachment_count": 0,
                "name": "Gebühr 25+",
                "property_account_expense_id": False,
                "property_account_income_id": False,
                "property_stock_inventory": 14,
                "property_stock_production": 15,
                "purchase_ok": True,
                "route_ids": [[6, False, []]],
                "sale_delay": 0,
                "sale_line_warn": "no-message",
                "sale_ok": True,
                "service_type": "manual",
                "supplier_taxes_id": [[6, False, [2]]],
                "taxes_id": [[6, False, []]],
                # "tic_category_id": False,
                "tracking": "none",
                "type": "service",
                "uom_id": 1,
                "uom_po_id": 1,
                "volume": 0,
                "weight": 0,
            },
        ],
    },
}