sample_data = {
    # -------- Create: Study course
    "study_course": {
        "module": "study.course",
        "search": [
            "study_course_code"
        ],  # do not create, when object is found using these elements
        "vals_list": [
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2000,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Psychology",
                "compensation": True,
                "coordination": False,
                "cost_center":("account.analytic.account", [("code", "BPSYd")]), #1,
                "date_of_introduction_session": False,
                "dekan": False,
                "department_id": ("department", [("name", "Psychologie d")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": False,
                "german": False,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": False,
                "language_en": False,
                "language_fr": True,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Science in Psychology",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": False,
                "price_module": False,
                "price_program": False,
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 0,
                "short_name": "B Sc in Psychology",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Pfäffikon")]),
                "study_course_code": "BSCPSYd",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Psychologie",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2000,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Psychology",
                "compensation": True,
                "coordination": False,
                "cost_center":("account.analytic.account", [("code", "BPSYf")]), #1,
                "date_of_introduction_session": False,
                "dekan": False,
                "department_id": ("department", [("name", "Psychologie f")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": False,
                "german": False,
                "grade_id": ("grade", [("name", "Master")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": False,
                "language_en": False,
                "language_fr": True,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Science in Psychology",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": False,
                "price_module": False,
                "price_program": False,
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 0,
                "short_name": "B Sc in Psychology",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Sierre")]),
                "study_course_code": "BSCPSYf",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Psychologie",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2000,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Psychology (bilingue français/allemand)",
                "compensation": True,
                "coordination": False,
                "cost_center":("account.analytic.account", [("code", "BPSYf")]), #1,
                "date_of_introduction_session": False,
                "dekan": False,
                "department_id": ("department", [("name", "Psychologie f")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": True,
                "german": True,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": False,
                "language_en": False,
                "language_fr": True,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Science in Psychology (bilingue, FR langue principale)",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": False,
                "price_module": False,
                "price_program": False,
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 9,
                "short_name": "B Sc in Psychology",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Sierre")]),
                "study_course_code": "BSCPSYbf",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Psychologie",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            }
        ],
    },
}