#!/usr/bin/env python
# # -*- coding: utf-8 -*-
from odoo_handler import get_objects
sample_data = {
    # -------- Create: studies
    "studies": {
        "module": "studies",
        "step": "second_run",
        "search": [
            "partner_id"
        ],  # do not create, when object is found using these elements
        "vals_list": [
            {
                "regular_student": True,
                "abandon": False,
                "accept_conditions": False,
                "annee_academique": False,
                "approval_exmatriculation": False,
                "approve_first_section": False,
                "continuing_education": False,
                "created_email": False,
                "created_moodle_account": False,
                "credit_application_available": False,
                "date": False,
                "date_end": ("semester", [("short_name", "FS20")]),
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS19")]),
                "date_definitely_allowed": "2016-04-03",
                "decision": False,
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "finished_immatriculations": False,
                "geburtsort": False,
                "guest": False,
                "horerstatus": False,
                "kohorte_id": False,
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": (
                    "res.partner",
                    [("name", "Student"), ("last_name", "Fleissig")],
                ),  # 70,
                "permission_date": False,
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                "reason_exmatriculation": 1,
                "remarks_credit_application": False,
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                "study_course_id": False,
                "total_ects_credits": 0,
                "valid_information": False,
                "validation_acquis": False,
            },
            {
                "state_of_study" : 'exmatriculated',
                "abandon": False,
                "regular_student": True,
                "accept_conditions": False,
                "annee_academique": False,
                "approval_exmatriculation": True,
                "approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": False,
                "date": False,
                "date_end": ("semester", [("short_name", "FS18")]),
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "HS13")]),
                "date_definitely_allowed": "2016-04-03",
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": 4.81,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": ("kohorte", [("name", "K03")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("name", "Eric"), ("last_name", "Tsiroulnikov⁣")],),
                "permission_date": '2013-02-07',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                "reason_exmatriculation": ("reason.exmatriculation", [("name", "Exmatrikulation bei erfolgreichem Abschluss")]),
                "remarks_credit_application": False,
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 9,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("short_name", "B Sc Economics and Management")]),
                "study_section_id": ("study.section", [("name", "2ème cycle")]),
                "total_ects_credits": 180,
                "valid_information": False,
                "validation_acquis": False,
            },
            {
                "state_of_study" : 'exmatriculated',
                "abandon": False,
                "regular_student": True,
                "accept_conditions": True,
                "annee_academique": False,
                "approval_exmatriculation": True,
                #"approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": True,
                "date": False,
                "date_end": ("semester", [("short_name", "FS16")]),
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS16")]),
                "date_definitely_allowed": "2016-04-03",
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": False,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": ("kohorte", [("name", "K24")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("name", "Martine"), ("last_name", "Freitag")],),
                "permission_date": '2015-12-18',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                "reason_exmatriculation": ("reason.exmatriculation", [("name", "Exmatrikulation auf studentisches Begehren")]),
                "remarks_credit_application": "Die zur Anrechnung vorgelegten Leistungen wurden vor mehr als 5 Jahren erarbeitet und entsprechen somit nicht den Voraussetzungen zu einer Anrechnung gemäss Artikel 21 des Studienreglements.",
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 9,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("study_course_code", "BLAWd")]),
                "study_section_id": ("study.section", [("name", "1. Teil"),('study_course_id', ("study.course", [("study_course_code", "BLAWd")]))]),
                "total_ects_credits": 180,
                "valid_information": True,
                "validation_acquis": False,
            },
            {
                "state_of_study" : 'student',
                "abandon": False,
                "regular_student": True,
                "accept_conditions": True,
                "annee_academique": False,
                "approval_exmatriculation": True,
                #"approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": True,
                "date": False,
                "date_end": False, # ("semester", [("short_name", "FS19")]),
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS19")]),
                "date_definitely_allowed": "2016-04-03",
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": False,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": ("kohorte", [("name", "K24")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("name", "Jürgen"), ("last_name", "Beer")],),
                "permission_date": '2019-01-23',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                "reason_exmatriculation": False, #("reason.exmatriculation", [("name", "Exmatrikulation auf studentisches Begehren")]),
                "remarks_credit_application": "",
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 9,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("study_course_code", "BLAWd")]),
                "study_section_id": ("study.section", [("name", "1. Teil"),('study_course_id', ("study.course", [("study_course_code", "BLAWd")]))]),
                "total_ects_credits": 180,
                "valid_information": True,
                "validation_acquis": False,
            },
            {
                "state_of_study" : 'student',
                "abandon": False,
                "regular_student": True,
                "accept_conditions": True,
                "annee_academique": False,
                "approval_exmatriculation": False,
                #"approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": True,
                "date": False,
                "date_end": False,
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS18")]),
                "date_definitely_allowed": "2016-04-03",
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": False,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": ("kohorte", [("name", "K21")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("name", "Laurence"), ("last_name", "Jaquet")],),
                "permission_date": '2017-01-23',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                #"reason_exmatriculation": ("reason.exmatriculation", [("name", "Exmatrikulation auf studentisches Begehren")]),
                "remarks_credit_application": "",
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 4,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("study_course_code", "BSCPSYf")]),
                "study_section_id": ("study.section", [("name", "2ème cycle"),('study_course_id', ("study.course", [("study_course_code", "BSCPSYf")]))]),
                "total_ects_credits": 62,
                "valid_information": True,
                "validation_acquis": False,
            },
            {
                "state_of_study" : 'student',
                "abandon": False,
                "regular_student": True,
                "accept_conditions": True,
                "annee_academique": False,
                "approval_exmatriculation": False,
                #"approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": True,
                "date": False,
                "date_end": False,
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS13")]),
                "date_definitely_allowed": "2013-04-03",
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": False,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": ("kohorte", [("name", "K06")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("name", "Martina"), ("last_name", "Fellay")],),
                "permission_date": '2017-01-23',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                #"reason_exmatriculation": ("reason.exmatriculation", [("name", "Exmatrikulation auf studentisches Begehren")]),
                "remarks_credit_application": "",
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 4,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("study_course_code", "BLAWf")]),
                "study_section_id": ("study.section", [("name", "1. Teil"),('study_course_id', ("study.course", [("study_course_code", "BLAWf")]))]),
                "total_ects_credits": 100,
                "valid_information": True,
                "validation_acquis": False,
            },
            {
                "state_of_study" : 'student',
                "guest": True,
                "abandon": False,
                "regular_student": True,
                "accept_conditions": True,
                "annee_academique": False,
                "approval_exmatriculation": True,
                #"approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": True,
                "date": False,
                "date_end": ("semester", [("short_name", "FS16")]),
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS16")]),
                "date_definitely_allowed": "2015-12-10",
                "temporally_allowed_date": "2015-11-16",
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": False,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": False, #("kohorte", [("name", "K24")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("last_name", 'Woog', '%')]),
                "permission_date": '2015-11-16',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                "reason_exmatriculation": ("reason.exmatriculation", [("name", "Exmatrikulation auf studentisches Begehren")]),
                "remarks_credit_application": "",
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 1,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("study_course_code", "BSCECOd")]),
                "study_section_id": ("study.section", [("name", "1. Teil"),('study_course_id', ("study.course", [("study_course_code", "BSCECOd")]))]),
                "total_ects_credits": 20,
                "valid_information": True,
                "validation_acquis": False,
            },
            {
                "state_of_study" : 'student',
                "guest": False,
                "abandon": False,
                "regular_student": True,
                "accept_conditions": True,
                "annee_academique": False,
                "approval_exmatriculation": True,
                "approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": True,
                "date": False,
                "date_end": ("semester", [("short_name", "FS16")]),
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS16")]),
                "date_definitely_allowed": "2015-12-10",
                #"date_dispensation": "2015-12-10",
                "temporally_allowed_date": "2015-11-16",
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": 4.94,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": ("kohorte", [("name", "K11")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("name", 'Patrizia', '%'), ("last_name", 'Bardola', '%')]),
                "permission_date": '2012-12-01',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                "reason_exmatriculation": ("reason.exmatriculation", [("name", "Exmatrikulation bei erfolgreichem Abschluss")]),
                "remarks_credit_application": "",
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 9,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("study_course_code", "BSCPSYd")]), #Bachelor of Science in Psychology
                "study_section_id": ("study.section", [("name", "2. Studienabschnitt"),('study_course_id', ("study.course", [("study_course_code", "BSCPSYd")]))]),
                "total_ects_credits": 20,
                "valid_information": True,
                "validation_acquis": False,
            },
            {
                "state_of_study" : 'student',
                "guest": False,
                "abandon": False,
                "regular_student": True,
                "accept_conditions": True,
                "annee_academique": False,
                "approval_exmatriculation": True,
                "approval_exmatriculation_date": "2016-11-17",
                "approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": True,
                "date": "2015-06-14",
                "date_end": ("semester", [("short_name", "FS15")]),
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS16")]),
                "date_definitely_allowed": "2015-12-10",
                #"date_dispensation": "2015-12-10",
                "temporally_allowed_date": "2015-11-16",
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": 4.94,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": ("kohorte", [("name", "K11")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("name", 'Thomas', '%'), ("last_name", 'Fader', '%')]),
                "permission_date": '2012-12-01',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                "reason_exmatriculation": ("reason.exmatriculation", [("name", "Exmatrikulation auf studentisches Begehren")]),
                "remarks_credit_application": "",
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": True,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 2,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("study_course_code", "BSCPSYd")]), #Bachelor of Science in Psychology
                "study_section_id": ("study.section", [("name", "2. Studienabschnitt"),('study_course_id', ("study.course", [("study_course_code", "BSCPSYd")]))]),
                "total_ects_credits": 20,
                "valid_information": True,
                "validation_acquis": False,
            },
        ],
    },
}

