sample_data = {
    # -------- Create: Study course
    "study_course": {
        "module": "study.course",
        "search": [
            "study_course_code"
        ],  # do not create, when object is found using these elements
        "vals_list": [
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2000,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Psychology",
                "compensation": True,
                "coordination": False,
                "cost_center":("account.analytic.account", [("code", "BPSYd")]), #1,
                "date_of_introduction_session": False,
                "dekan": False,
                "department_id": ("department", [("name", "Psychologie d")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": False,
                "german": False,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": False,
                "language_en": False,
                "language_fr": True,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Science in Psychology",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": False,
                "price_module": False,
                "price_program": False,
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 0,
                "short_name": "B Sc in Psychology",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Pfäffikon")]),
                "study_course_code": "BSCPSYd",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Psychologie",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            #     {'dekan_ids': [[0,
            #          'virtual_878',
            #             {'__last_update': False,
            #             'date_start': '2014-05-06',
            #             'date_to': False,
            #             'function': 'Dekan',
            #             'name': 'CélineDK',
            #             'partner_id': 40,
            #             'signature': ''
            #             'signature_fname': 'signature_marc_bors.jpeg'}]],
            #     },
            #     'sk_ids': [[0,
            #                 'virtual_865',
            #                 {'__last_update': False,
            #                 'date_start': '2011-02-08',
            #                 'date_to': False,
            #                 'function': 'Student Coordinator',
            #                 'name': 'BartSK',
            #                 'partner_id': 43,
            #                 'signature': '
            #                 'signature_fname': 'signature_rodrigo_rodriguez.png'}]]
            #                 }]
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2000,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Psychology",
                "compensation": True,
                "coordination": False,
                "cost_center":("account.analytic.account", [("code", "BPSYf")]), #1,
                "date_of_introduction_session": False,
                "dekan": False,
                "department_id": ("department", [("name", "Psychologie f")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": False,
                "german": False,
                "grade_id": ("grade", [("name", "Master")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": False,
                "language_en": False,
                "language_fr": True,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Science in Psychology",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": False,
                "price_module": False,
                "price_program": False,
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 0,
                "short_name": "B Sc in Psychology",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Sierre")]),
                "study_course_code": "BSCPSYf",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Psychologie",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2000,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Psychology (bilingue français/allemand)",
                "compensation": True,
                "coordination": False,
                "cost_center":("account.analytic.account", [("code", "BPSYf")]), #1,
                "date_of_introduction_session": False,
                "dekan": False,
                "department_id": ("department", [("name", "Psychologie f")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": True,
                "german": True,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": False,
                "language_en": False,
                "language_fr": True,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Science in Psychology (bilingue, FR langue principale)",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": False,
                "price_module": False,
                "price_program": False,
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 9,
                "short_name": "B Sc in Psychology",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Sierre")]),
                "study_course_code": "BSCPSYbf",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Psychologie",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2540,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Economics and Management",
                "compensation": True,
                "coordination": ("res.partner", [("last_name", "Student Manager"), ("name", "FR")]),
                "cost_center":("account.analytic.account", [("code", "BECOf")]), #1,
                "date_of_introduction_session": False,
                "dekan": ("res.users", [("login", "thierry")]),
                "faculty_manager_id": ("res.users", [("login", "jean_paul")]),
                "department_id": ("department", [("name", "Economie")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": True,
                "german": True,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": False,
                "language_en": False,
                "language_fr": True,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Science in Economics and Management",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": ("product.product", [("default_code", "113")]),
                "price_part_time": ("product.product", [("default_code", "111")]),
                "price_module": ("product.product", [("default_code", "112")]),
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 9,
                "short_name": "B Sc Economics and Management",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Sierre")]),
                "study_course_code": "BSCECOMf",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Economie politique et gestion d'entreprise",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2600,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Law",
                "compensation": True,
                "coordination": ("res.partner", [("last_name", "Student Manager"), ("name", "DE")]),
                "cost_center":("account.analytic.account", [("code", "BLAWd")]), #1,
                "date_of_introduction_session": False,
                "dekan": ("res.users", [("login", "rodrigo")]),
                "faculty_manager_id": ("res.users", [("login", "malin")]),
                "department_id": ("department", [("name", "Rechtswissenschaften")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "BLaw",
                "french": True,
                "german": True,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": False,
                "language_en": False,
                "language_fr": True,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Law",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": ("product.product", [("default_code", "113")]),
                "price_part_time": ("product.product", [("default_code", "111")]),
                "price_module": ("product.product", [("default_code", "112")]),
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 9,
                "short_name": "B Sc Economics and Management",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Pfäffikon")]),
                "study_course_code": "BLAWd",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": 'http://fernuni.ch/law/',
                "study_goal": "Bachelor of Law",
                "subject_study": "Rechtswissenschaft",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2600,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Law",
                "compensation": True,
                "coordination": ("res.partner", [("last_name", "Student Manager"), ("name", "DE")]),
                "cost_center":("account.analytic.account", [("code", "BLAWf")]), #1,
                "date_of_introduction_session": False,
                "dekan": ("res.users", [("login", "rodrigo")]),
                "faculty_manager_id": ("res.users", [("login", "malin")]),
                "department_id": ("department", [("name", "Droit")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "BLaw",
                "french": True,
                "german": True,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": False,
                "language_en": False,
                "language_fr": True,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Law",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": ("product.product", [("default_code", "113")]),
                "price_part_time": ("product.product", [("default_code", "111")]),
                "price_module": ("product.product", [("default_code", "112")]),
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 9,
                "short_name": "B Sc Economics and Management",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Pfäffikon")]),
                "study_course_code": "BLAWf",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": 'http://fernuni.ch/law/',
                "study_goal": "Bachelor of Law",
                "subject_study": "Rechtswissenschaft",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2505,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Economics",
                "compensation": True,
                "coordination": ("res.partner", [("last_name", "Student Manager"), ("name", "FR")]),
                "cost_center":("account.analytic.account", [("code", "BLAWf")]), #1,
                "date_of_introduction_session": False,
                "dekan": ("res.users", [("login", "renate")]),
                "faculty_manager_id": ("res.users", [("login", "petra")]),
                "department_id": ("department", [("name", "Droit")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": True,
                "german": True,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": True,
                "language_en": False,
                "language_fr": False,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Science in Economics",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": ("product.product", [("default_code", "113")]),
                "price_part_time": ("product.product", [("default_code", "111")]),
                "price_module": ("product.product", [("default_code", "112")]),
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 9,
                "short_name": "B Sc in Economics",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Sierre")]),
                "study_course_code": "BLAWf",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Droit suisse",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2505,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Economics",
                "compensation": True,
                "coordination": ("res.partner", [("last_name", "Student Manager"), ("name", "FR")]),
                "cost_center":("account.analytic.account", [("code", "BECOd")]), #1,
                "date_of_introduction_session": False,
                "dekan": ("res.users", [("login", "renate")]),
                "faculty_manager_id": ("res.users", [("login", "petra")]),
                "department_id": ("department", [("name", "Wirtschaftswissenschaften")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": False,
                "german": True,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": True,
                "language_en": False,
                "language_fr": False,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Bachelor of Science in Economics",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": ("product.product", [("default_code", "113")]),
                "price_part_time": ("product.product", [("default_code", "111")]),
                "price_module": ("product.product", [("default_code", "112")]),
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 9,
                "short_name": "B Sc in Economics",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Pfäffikon")]),
                "study_course_code": "BSCECOd",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Wirtschaftswissenschaft",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
            {
                "access_further_studies_de": False,
                "access_further_studies_en": False,
                "access_further_studies_fr": False,
                "access_requirements_de": False,
                "access_requirements_en": False,
                "access_requirements_fr": False,
                "active": True,
                "additional_documents_online_registration": False,
                "bfs_number": 2505,
                "blocking_semester_ids": [[6, False, []]],
                "canadian_credits": 0,
                "certificate": "Bachelor of Science in Economics",
                "compensation": True,
                "coordination": ("res.partner", [("last_name", "Student Manager"), ("name", "FR")]),
                "cost_center":("account.analytic.account", [("code", "BLAWd")]), #1,
                "date_of_introduction_session": False,
                "dekan": ("res.users", [("login", "renate")]),
                "faculty_manager_id": ("res.users", [("login", "petra")]),
                "department_id": ("department", [("name", "Rechtswissenschaften")]),
                "ects": 180,
                "english": False,
                "final_degree_short_name": "B Sc",
                "french": False,
                "german": True,
                "grade_id": ("grade", [("name", "Bachelor")]),
                "guest": False,
                "ignore_sis_import": False,
                "introduction_session_place": False,
                "is_dekansalaryrelevant": True,
                "iuv_group": "I",
                "language_de": True,
                "language_en": False,
                "language_fr": False,
                "level_qualification_de": False,
                "level_qualification_en": False,
                "level_qualification_fr": False,
                "main_de": False,
                "main_en": False,
                "main_fr": False,
                "max_failed_tries": False,
                "max_study_duration": 15,
                "mode_study_de": False,
                "mode_study_en": False,
                "mode_study_fr": False,
                "modules_students": True,
                "moodle_general_courses": False,
                "name": "Rechtswissenschaften (Kooperation Pädagogische Hochschule Thurgau)",
                "offical_length_worlkload_de": False,
                "offical_length_worlkload_en": False,
                "offical_length_worlkload_fr": False,
                "price_application": False,
                "price_holiday": ("product.product", [("default_code", "113")]),
                "price_part_time": ("product.product", [("default_code", "111")]),
                "price_module": ("product.product", [("default_code", "112")]),
                "professional_status_de": False,
                "professional_status_en": False,
                "professional_status_fr": False,
                "programme_requirements_de": False,
                "programme_requirements_en": False,
                "programme_requirements_fr": False,
                "remarks": False,
                "semesters_full_time": 0,
                "semesters_part_time": 9,
                "short_name": "B Sc in Economics",
                "student_resources_type_ids": [[6, False, []]],
                "study_center_id": ("study.center", [("name", "Pfäffikon")]),
                "study_course_code": "BLAWdPHTG",
                "study_course_mail": "studentservices@fernuni.ch",
                "study_course_phone": "0840 840 820",
                "study_course_url": False,
                "study_goal": "Bachelor of Science",
                "subject_study": "Rechtswissenschaft",
                "training_course": False,
                "university_id": ("university", [("name", "Universitäre Fernstudien Schweiz")]),
                "visible_online_registration": True,
                "weiterbildung": False,
                "workgroup_ids": [[6, False, []]],
            },
        ],
    },
}