            {
                "state_of_study" : 'student',
                "guest": True,
                "abandon": False,
                "regular_student": True,
                "accept_conditions": True,
                "annee_academique": False,
                "approval_exmatriculation": True,
                "approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": True,
                "date": False,
                "date_end": ("semester", [("short_name", "FS16")]),
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS16")]),
                "date_definitely_allowed": "2015-12-10",
                "date_dispensation": "2015-12-10",
                "temporally_allowed_date": "2015-11-16",
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": 4.94,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": ("kohorte", [("name", "K11")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("name", 'Patrizia'), ("last_name", 'Bardola', '%')]),
                "permission_date": '2012-12-01',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                "reason_exmatriculation": ("reason.exmatriculation", [("name", "Exmatrikulation bei erfolgreichem Abschluss")]),
                "remarks_credit_application": "",
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 9,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("study_course_code", "BSCPSYd")]),
                "study_section_id": ("study.section", [("name", "1. Teil"),('study_course_id', ("study.course", [("study_course_code", "BSCPSYd")]))]),
                "total_ects_credits": 20,
                "valid_information": True,
                "validation_acquis": False,
            },
