            {
                "active": True,
                "choose_student_module": False,
                "content_of_study": False,
                "dependency_finished_ids": [[6, False, []]],
                "dependency_ids": [[6, False, []]],
                "description": False,
                "dummy": False,
                "ect_credist": 10,
                "enable_module": False,
                "group": "1",
                "guest": False,
                "kohorte_ids": [[6, False, []]],
                "learning_outcomes": False,
                "message_attachment_count": 0,
                "module_code": 'ENTW',
                "module_id": ("module", [("module_code", "ENTW")]), #1,,
                "module_number": 'M04',
                "modules_students": True,
                "moodle_id": 0,
                "name": "Entwicklungspsychologie",
                "publish_on_website": False,
                "repetition": "3", #spring and autumn semester
                "requirements": False,
                "semester": 2,
                "semester_id": ("semester", [("short_name", "FS19")]),
                "short_name": "Entwicklungspsychologie",
                "study_course_ids": [
                    [6, False, get_objects("study.course", login=["matthias", "login"])]
                ],
                "study_section_id": ("study.section",
                    [("name", "Propädeutikum"),('study_course_id', ("study.course", [("study_course_code", "BSCPSYd")]))]), #1, # SUCHEN!!
                "survey_cas_question_ids": [[6, False, []]],
                "survey_specific_question_ids": [[6, False, []]],
                "teaching_material": False,
                "type": '1', # Wat is that pfichtfach
                "type_of_exam": "exam",
                "validation_state": "not_validated",
                "number_of_events_to_visit": "3",
            },
