            {
                "academic_title": False,
                "customer_rank" : 1,
                "active": True,
                "additional_info": False,
                "ahv_number": "756.1180.1376.18",
                "bfs_student_auth_id_code": False,
                "bfs_before_study_id": False,
                "birthdate": "1968-07-26",
                "certification_date_before": 0,
                "city": 'Grimisuat',
                "gender": "2",
                "lang": "ch_FR",
                "last_name": "Jaquet",
                "mobile": '+41793304156',
                "name": "Laurence",
                "profession": False,
                "prospect": False,
                "ref": False,
                "remarks_marketing": False,
                "return_certificate": False,
                "sale_warn": "no-message",
                "signature_for_reports": False,
                "signature_for_reports_fname": False,
                "country_id": 43,
                "street": 'Rue des Condémines 16',
                "street2": False,
                "title": 2,
                "student": True,
                "zip" : "1971",
                "matriculation_number": "91-312-140",
                "unmarried_name": 'Hitter',
                "login": "191-312-140",
                #"groups": ["fsch_customer.group_fsch_student",],
            },

            {
                "state_of_study" : 'imatriculated',
                "abandon": False,
                "regular_student": True,
                "accept_conditions": True,
                "annee_academique": False,
                "approval_exmatriculation": True,
                #"approve_first_section": True,
                "continuing_education": False,
                "created_email": True,
                "created_moodle_account": True,
                "credit_application_available": True,
                "date": False,
                "date_end": ,
                "date_envoi_diplome": False,
                "date_reception_diplome": False,
                "date_start": ("semester", [("short_name", "FS18")]),
                "decision": 'permitted',
                "diplome": False,
                "disqualification": False,
                "einschreibestatus": False,
                "envoi_va_uni_inscription": False,
                "envoi_va_uni_validation": False,
                "erstsemester": False,
                "exams_failed": False,
                "fachstudiensemester": 0,
                "final_grade": False,
                "finished_immatriculations": True,
                "geburtsort": False,
                "horerstatus": False,
                "kohorte_id": ("kohorte", [("name", "K21")]),
                "missing_documents": False,
                "modules_students": False,
                "motif": False,
                "nom_du_diplome": False,
                "notes": False,
                "part_time": False,
                "partner_id": ("res.partner", [("name", "Laurence"), ("last_name", "Jaquet")],),
                "permission_date": '2019-01-23',
                "permission_remark": False,
                "pieces_manquantes_inscription": False,
                "pieces_manquantes_validation": False,
                #"predicate": field is calculated
                #"reason_exmatriculation": ("reason.exmatriculation", [("name", "Exmatrikulation auf studentisches Begehren")]),
                "remarks_credit_application": "",
                "remarks_exmatriculation": False,
                "remarques_inscription": False,
                "remarques_validation": False,
                "second_matriculation": False,
                "second_matriculation_branch_study": False,
                "second_matriculation_grade": False,
                "second_matriculation_school_city": False,
                "second_matriculation_school_name": False,
                "second_matriculation_start_study": False,
                "semester": 4,
                "signature_for_study": False,
                "signature_for_study_fname": False,
                'study_course_id': ("study.course", [("study_course_code", "BSCPSYf")]),
                "study_section_id": ("study.section", [("name", "1. Teil"),('study_course_id', ("study.course", [("study_course_code", "BSCPSYf")]))]),
                "total_ects_credits": 62,
                "valid_information": True,
                "validation_acquis": False,
            }
